apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx-004
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
      annotations:
        flomesh.io/inject: "true"
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80