apiVersion: v1
kind: Pod
metadata:
  name: pipy-sidecar-005
  labels:
    tier: frontend
  annotations:
    flomesh.io/inject: "true"
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello:plain-text
    ports:
    - containerPort: 80