apiVersion: flomesh.io/v1alpha1
kind: Proxy
metadata:
  name: pipy-standalone-002
spec:
  mode: Standalone
  tplMode: Raw
  replicas: 1
  image: flomesh/pipy-pjs:latest
  port: 6000
  config:
    config.js: |
      pipy()
        .listen(6000)
          .decodeHttpRequest()
          .replaceMessage(new Message('Hello!\n'))
          .encodeHttpResponse()




