apiVersion: flomesh.io/v1alpha1
kind: Proxy
metadata:
  name: pipy-standalone-004
spec:
  mode: Standalone
  tplMode: Raw
  replicas: 1
  image: flomesh/pipy:latest
  port: 6000
  config:
    config.cfg: |
      pipy
        pipeline :6000
          decode-http-request
            prefix = a
          script
            source = pass.js
          encode-http-response
            prefix = a
    pass.js: |
      // Called once for every new session
      export default (output) => (

        // Called once for every object running through on the stream
        (input) => output(input)

      );
