# permissions for end users to view proxyprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxyprofile-viewer-role
rules:
- apiGroups:
  - flomesh.io
  resources:
  - proxyprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flomesh.io
  resources:
  - proxyprofiles/status
  verbs:
  - get
