apiVersion: flomesh.io/v1
kind: Proxy
metadata:
  name: pipy-005
spec:
  mode: Standalone
  tplMode: Raw
  replicas: 1
  image: flomesh/pipy:latest
  port: 8080
  config:
    config.cfg: |
      #
      # curl -H "app: app1" http://localhost:8080/
      # curl -H "app: order-app" http://localhost:8080/
      #
      pipeline 0.0.0.0:8080
          decode-http-request
              variable_protocol = http_protocol
              variable_headers = http_headers.*
          proxy
              to = ${http_headers.app}
          encode-http-response
              protocol = ${http_protocol}
              variable_connection = http_headers.connection
              variable_keep_alive = http_headers.keep-alive
      pipeline app1
          hello
              message = Hello, app1
      pipeline order-app
          hello
              message = Hello, order-app
