apiVersion: flomesh.io/v1
kind: Proxy
metadata:
  name: pipy-standalone-011
spec:
  mode: Standalone
  tplMode: Raw
  replicas: 1
  image: flomesh/pipy:latest
  port: 6000
  config:
    config.cfg: |
      pipy
       pipeline :6000
         decode-http-request
           prefix = a
         serve-static
           # path = html
           prefix = a
           ext.html = text/html
           ext.css = text/css
           ext.xml = text/xml
           ext.txt = text/plain
           ext.gif = image/gif
           ext.png = image/png
           ext.jpg = image/jpeg
           ext.svg = image/svg+xml
           ext.woff = font/woff
           ext.woff2 = font/woff2
           ext.js = application/javascript
           ext.json = application/json
         encode-http-response
           prefix = a

    50x.html: |
      <!DOCTYPE html>
      <html>
      <head>
      <title>Error</title>
      <style>
          body {
              width: 35em;
              margin: 0 auto;
              font-family: Tahoma, Verdana, Arial, sans-serif;
          }
      </style>
      </head>
      <body>
      <h1>An error occurred.</h1>
      <p>Sorry, the page you are looking for is currently unavailable.<br/>
      Please try again later.</p>
      <p>If you are the system administrator of this resource then you should check
      the error log for details.</p>
      <p><em>Faithfully yours, nginx.</em></p>
      </body>
      </html>
    index.html: |
      <!DOCTYPE html>
      <html>
        <head>
          <title>Hello</title>
        </head>
        <body>
          <p>Hello!</p>
        </body>
      </html>
