apiVersion: flomesh.io/v1
kind: Proxy
metadata:
  name: pipy-standalone-013
spec:
  mode: Standalone
  tplMode: Raw
  replicas: 1
  image: flomesh/pipy:latest
  port: 6000
  config:
    config.cfg: |
      pipy
        #
        # HTTP port with message couting
        #
        pipeline :6000
          decode-http-request
            prefix = a
          count
            when = MessageStart
            label = TPS
          hello
            message = Hello!\n
          encode-http-response
            prefix = a

        #
        # Metric port for Prometheus
        #

        pipeline :9432
          decode-http-request
            prefix = a
          prometheus
          encode-http-response
            prefix = a


