apiVersion: flomesh.io/v1
kind: Proxy
metadata:
  name: pipy-013
spec:
  mode: Standalone
  tplMode: Raw
  replicas: 1
  image: flomesh/pipy:latest
  port: 8080
  config:
    config.cfg: |
      pipeline 0.0.0.0:8080
          decode-http-request
              variable_protocol = http_protocol
              variable_headers = http_headers.*
          script
              source = encode-msg.js
          script
              source = decode-msg.js
          encode-http-response
              protocol = ${http_protocol}
              variable_connection = http_headers.connection
              variable_keep_alive = http_headers.keep-alive
