apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy-sidecar-injector
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: proxy-injector
        imagePullPolicy: IfNotPresent