apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: proxy-profile-001
spec:
  selector:
    matchLabels:
      app: pipy-003-hello-ip
  namespace: default
  config:
    config.tpl: |
      pipy()
        .listen({{ .ProxyPort }})
        .connect(() => "127.0.0.1:{{ .TargetPort }}")