apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

components:
- ../../components/dev

images:
- name: operator-manager
  newName: flomesh/operator-manager
  newTag: dev
- name: proxy-injector
  newName: flomesh/proxy-injector
  newTag: dev
