apiVersion: flomesh.io/v1
kind: Proxy
metadata:
  name: pipy-ingress-008
spec:
  mode: Ingress
  tplMode: Raw
  image: flomesh/pipy:latest
  port: 9090
  config:
    config.cfg: |
      pipeline 0.0.0.0:9090
          decode-http-request
              #这个语义类似：context['http_protocol'] = parse_protocol()
              variable_protocol = http_protocol
              variable_path = http_path
              variable_headers = http_headers.*
          proxy
              to = ${http_path}
          encode-http-response
              protocol = ${http_protocol}
              variable_connection = http_headers.connection
              variable_keep_alive = http_headers.keep-alive

      pipeline /hello
          hello
              message = Hello!\n

      pipeline /test
          hello
              message = Test\n
