apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy-sidecar-007
  labels:
    app: pipy-011-serve-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipy-011-serve-static
  template:
    metadata:
      labels:
        app: pipy-011-serve-static
        sys: pipy-sidecar-samples
      annotations:
        flomesh.io/inject: "true"
    spec:
      containers:
      - name: pipy-011
        image: flomesh/pipy:latest
        ports:
        - containerPort: 6000
        command: ["/usr/local/bin/pipy", "/etc/pipy/test/011-serve-static/pipy.cfg"]