apiVersion: v1
kind: Pod
metadata:
  name: pipy-sidecar-009
  labels:
    tier: frontend
    sys: pipy-sidecar-samples
  annotations:
    flomesh.io/inject: "true"
spec:
  containers:
  - name: pipy-011
    image: flomesh/pipy:latest
    ports:
    - containerPort: 6000
    command: [ "/usr/local/bin/pipy", "/etc/pipy/test/011-serve-static/pipy.cfg" ]