apiVersion: v1
kind: Pod
metadata:
  name: pipy-sidecar-009
  labels:
    tier: frontend
    sys: pipy-sidecar-samples
  annotations:
    flomesh.io/inject: "true"
spec:
  containers:
  - name: pipy-011
    image: flomesh/pipy-pjs:latest
    ports:
    - containerPort: 6080
    command: [ "/usr/local/bin/pipy", "/etc/pipy/test/003-hello-ip/pipy.js", "--reuse-port" ]