apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: proxy-profile-sidecar-100
spec:
  selector:
    matchLabels:
      sys: pipy-sidecar-samples
  config:
    config.tpl: |
      pipy()
        .listen({{ .ProxyPort }})
        .connect(() => "127.0.0.1:{{ .TargetPort }}")