apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-configmap
  namespace: system
data:
  pipy-sidecar-cfg.yaml: |
    containers:
    - name: pipy-sidecar
      image: flomesh/pipy:latest
      imagePullPolicy: Always
      ports:
      - containerPort: {{ .ContainerPort }}
      env:
      - name: PIPY_PORT
        value: {{ .PipyPort }}
      - name: PIPY_TARGET_PORT
        value: {{ .PipyTargetPort }}
      command: ["/bin/sh"]
      args:
      - -c
      - >-
          curl -k -X POST https://flomesh-pipy-cfg-service.flomesh-system/pipy \
              -H "Content-Type: application/json" \
              -d "{ \"port\":{{ .PipyPort }}, \"targetPort\":{{ .PipyTargetPort }} }" \
              -o /config.cfg &&
          cat /config.cfg &&
          echo "starting pipy sidecar with config.cfg..." &&
          /usr/local/bin/pipy /config.cfg
