apiVersion: v1
kind: Service
metadata:
  name: pipy-sidecar-injector-service
  namespace: system
spec:
  ports:
  - port: 443
    targetPort: 7443
  selector:
    proxy-injector: pipy-sidecar-injector